# Generated by Django 4.1.2 on 2022-10-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_alter_api_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_env',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.config', verbose_name='执行环境'),
        ),
    ]
