# Generated by Django 4.1.2 on 2022-10-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_alter_api_api_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_env',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.config', verbose_name='执行环境'),
        ),
    ]
