# Generated by Django 4.1.2 on 2022-11-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_alter_case_case_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.project', verbose_name='所属项目'),
        ),
    ]
