# Generated by Django 4.1.2 on 2022-11-03 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_alter_api_project_alter_case_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='快捷名称')),
                ('link', models.TextField(default='', verbose_name='链接')),
                ('color', models.CharField(default='', max_length=100, verbose_name='背景色')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '快捷方式列表',
                'verbose_name_plural': '快捷方式列表',
                'db_table': 'tabs',
                'ordering': ['-id'],
            },
        ),
    ]
