# Generated by Django 4.1.2 on 2022-11-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_tags'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tags',
            table='tags',
        ),
    ]
