# Generated by Django 4.1.2 on 2022-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_alter_tags_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='personal',
            field=models.CharField(default='2', max_length=5, verbose_name='是否私有-1：私有 2：共有'),
        ),
    ]
