# Generated by Django 4.1.5 on 2023-02-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_alter_files_file_alter_files_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='项目名称'),
        ),
    ]
