# Generated by Django 4.1.5 on 2023-02-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='项目名称'),
        ),
    ]
