# Generated by Django 4.2 on 2023-04-12 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_alter_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='端名称')),
                ('src', models.TextField(default='', verbose_name='链接')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='手机号')),
                ('msg', models.CharField(default='', max_length=10, verbose_name='验证码')),
                ('config', models.JSONField(default=list, verbose_name='配置')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '验证码工具',
                'verbose_name_plural': '验证码工具',
                'db_table': 'toolsMessage',
                'ordering': ['-id'],
            },
        ),
    ]
