# Generated by Django 4.2 on 2023-04-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0016_toolsmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmessage',
            name='src',
            field=models.TextField(default='', verbose_name='logo'),
        ),
    ]
