# Generated by Django 4.2 on 2023-04-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0018_alter_toolsmessage_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolsmessage',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='toolsmessage',
            name='phone',
        ),
    ]
