# Generated by Django 4.2 on 2023-04-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_remove_toolsmessage_msg_remove_toolsmessage_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsmessage',
            options={'ordering': ['id'], 'verbose_name': '验证码工具', 'verbose_name_plural': '验证码工具'},
        ),
    ]
