# Generated by Django 4.2 on 2023-04-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_alter_toolsmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmessage',
            name='src',
            field=models.TextField(verbose_name='logo'),
        ),
    ]
