# Generated by Django 4.2 on 2023-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0021_alter_toolsmessage_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmessage',
            name='src',
            field=models.TextField(blank=True, verbose_name='logo'),
        ),
    ]
