# Generated by Django 4.2 on 2023-04-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0022_alter_toolsmessage_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='api',
        ),
    ]
