# Generated by Django 4.2 on 2023-04-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0023_remove_files_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='env',
        ),
    ]
