# Generated by Django 4.2 on 2023-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0024_remove_project_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='status',
            field=models.CharField(blank=True, max_length=5, verbose_name='执行状态'),
        ),
    ]
