# Generated by Django 4.2 on 2023-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0025_api_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='status',
            field=models.CharField(blank=True, max_length=10, verbose_name='执行状态'),
        ),
    ]
