# Generated by Django 4.2 on 2023-04-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0027_alter_api_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='response',
        ),
    ]
