# Generated by Django 4.2 on 2023-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0028_remove_api_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='报告url'),
        ),
    ]
